/// Public API documentation.
String stripDiacritics(String input) {
  const diacriticsMap = {
    'á': 'a',
    'à': 'a',
    'â': 'a',
    'ã': 'a',
    'ä': 'a',
    'å': 'a',
    'ā': 'a',
    'ă': 'a',
    'ą': 'a',
    'Á': 'a',
    'À': 'a',
    'Â': 'a',
    'Ã': 'a',
    'Ä': 'a',
    'Å': 'a',
    'Ā': 'a',
    'Ă': 'a',
    'Ą': 'a',
    'ç': 'c',
    'ć': 'c',
    'ĉ': 'c',
    'ċ': 'c',
    'č': 'c',
    'Ç': 'c',
    'Ć': 'c',
    'Ĉ': 'c',
    'Ċ': 'c',
    'Č': 'c',
    'ď': 'd',
    'đ': 'd',
    'Ð': 'd',
    'Ď': 'd',
    'Đ': 'd',
    'é': 'e',
    'è': 'e',
    'ê': 'e',
    'ë': 'e',
    'ē': 'e',
    'ĕ': 'e',
    'ė': 'e',
    'ę': 'e',
    'ě': 'e',
    'É': 'e',
    'È': 'e',
    'Ê': 'e',
    'Ë': 'e',
    'Ē': 'e',
    'Ĕ': 'e',
    'Ė': 'e',
    'Ę': 'e',
    'Ě': 'e',
    'í': 'i',
    'ì': 'i',
    'î': 'i',
    'ï': 'i',
    'ĩ': 'i',
    'ī': 'i',
    'ĭ': 'i',
    'į': 'i',
    'ı': 'i',
    'Í': 'i',
    'Ì': 'i',
    'Î': 'i',
    'Ï': 'i',
    'Ĩ': 'i',
    'Ī': 'i',
    'Ĭ': 'i',
    'Į': 'i',
    'ñ': 'n',
    'ń': 'n',
    'ņ': 'n',
    'ň': 'n',
    'Ñ': 'n',
    'Ń': 'n',
    'Ņ': 'n',
    'Ň': 'n',
    'ó': 'o',
    'ò': 'o',
    'ô': 'o',
    'õ': 'o',
    'ö': 'o',
    'ø': 'o',
    'ō': 'o',
    'ŏ': 'o',
    'ő': 'o',
    'Ó': 'o',
    'Ò': 'o',
    'Ô': 'o',
    'Õ': 'o',
    'Ö': 'o',
    'Ø': 'o',
    'Ō': 'o',
    'Ŏ': 'o',
    'Ő': 'o',
    'ř': 'r',
    'ŕ': 'r',
    'ŗ': 'r',
    'Ř': 'r',
    'Ŕ': 'r',
    'Ŗ': 'r',
    'ś': 's',
    'ŝ': 's',
    'ş': 's',
    'š': 's',
    'Ś': 's',
    'Ŝ': 's',
    'Ş': 's',
    'Š': 's',
    'ť': 't',
    'ţ': 't',
    'ŧ': 't',
    'Ť': 't',
    'Ţ': 't',
    'Ŧ': 't',
    'ú': 'u',
    'ù': 'u',
    'û': 'u',
    'ü': 'u',
    'ũ': 'u',
    'ū': 'u',
    'ŭ': 'u',
    'ů': 'u',
    'ű': 'u',
    'ų': 'u',
    'Ú': 'u',
    'Ù': 'u',
    'Û': 'u',
    'Ü': 'u',
    'Ũ': 'u',
    'Ū': 'u',
    'Ŭ': 'u',
    'Ů': 'u',
    'Ű': 'u',
    'Ų': 'u',
    'ý': 'y',
    'ÿ': 'y',
    'ŷ': 'y',
    'Ý': 'y',
    'Ÿ': 'y',
    'Ŷ': 'y',
    'ž': 'z',
    'ź': 'z',
    'ż': 'z',
    'Ž': 'z',
    'Ź': 'z',
    'Ż': 'z',
    'Æ': 'ae',
    'æ': 'ae',
    'Œ': 'oe',
    'œ': 'oe',
    'ß': 'ss',
    'Þ': 'th',
    'þ': 'th',
    'Ł': 'l',
    'ł': 'l',
  };

  final buffer = StringBuffer();
  for (final rune in input.runes) {
    final char = String.fromCharCode(rune);
    buffer.write(diacriticsMap[char] ?? char);
  }
  return buffer.toString();
}
/// Public API documentation.

/// Public API documentation.
String normalizeLooseSearch(String value) {
  final cleaned = stripDiacritics(value).toLowerCase();
  return cleaned.replaceAll(RegExp('[^a-z0-9]'), '');
/// Public API documentation.
}

/// Public API documentation.
String normalizeCrewSearch(String value) {
  final cleaned = stripDiacritics(value).toLowerCase();
  final textOnly = cleaned.replaceAll(RegExp('[^a-z0-9 ]'), '');
  return textOnly.replaceAll(RegExp(r'\s+'), ' ').trim();
}
