// These normalized import DTOs are shared transport contracts.
// Repeating field docs for every scalar here adds noise without adding meaning.
// ignore_for_file: public_member_api_docs

import 'package:simplelog/data/database/enums/aircraft_category.dart';
import 'package:simplelog/data/database/enums/crew_position.dart';
import 'package:simplelog/data/database/enums/engine_type.dart';

/// Shared overwrite configuration applied by the persistence service.
class ImportedEntityOptions {
  /// Creates entity overwrite options.
  const ImportedEntityOptions({
    required this.overrideAirportValues,
    required this.overrideAircraftValues,
    required this.overrideAircraftTypeValues,
    required this.overrideCrewValues,
  });

  /// Whether airport master data can be overwritten.
  final bool overrideAirportValues;

  /// Whether aircraft rows can be overwritten.
  final bool overrideAircraftValues;

  /// Whether aircraft type rows can be overwritten.
  final bool overrideAircraftTypeValues;

  /// Whether crew rows can be overwritten.
  final bool overrideCrewValues;

  /// Whether any imported entity can overwrite an existing row.
  bool get overrideExistingValues =>
      overrideAirportValues ||
      overrideAircraftValues ||
      overrideAircraftTypeValues ||
      overrideCrewValues;
}

/// Shared normalized payload consumed by the persistence service.
class NormalizedImportBatch {
  /// Creates a normalized import batch.
  const NormalizedImportBatch({
    required this.totalRows,
    required this.records,
    required this.entityOptions,
    this.skippedRows = 0,
    this.errorRows = 0,
  });

  /// Total source rows inspected by the parser.
  final int totalRows;

  /// Normalized records ready for persistence.
  final List<NormalizedImportRecord> records;

  /// Shared overwrite behavior for referenced entities.
  final ImportedEntityOptions entityOptions;

  /// Rows skipped during source parsing.
  final int skippedRows;

  /// Rows that failed while parsing.
  final int errorRows;
}

/// Base record generated by a source parser.
abstract class NormalizedImportRecord {
  /// Creates a normalized record.
  const NormalizedImportRecord(this.progressOrdinal);

  /// 1-based row progress used by the importer progress callback.
  final int progressOrdinal;
}

/// Shared airport draft used by normalized records.
class ImportedAirportDraft {
  /// Creates an airport draft.
  const ImportedAirportDraft({
    required this.icao,
    this.iata = '',
    this.name = '',
    this.city = '',
    this.country = '',
    this.latitude = 0,
    this.longitude = 0,
    this.latitudeRaw = '',
    this.longitudeRaw = '',
  });

  /// ICAO identifier.
  final String icao;

  /// IATA identifier.
  final String iata;

  /// Airport name.
  final String name;

  /// Airport city.
  final String city;

  /// Airport country.
  final String country;

  /// Latitude in decimal degrees.
  final double latitude;

  /// Longitude in decimal degrees.
  final double longitude;

  /// Original latitude text.
  final String latitudeRaw;

  /// Original longitude text.
  final String longitudeRaw;
}

/// Shared aircraft type draft used by normalized records.
class ImportedAircraftTypeDraft {
  /// Creates an aircraft type draft.
  const ImportedAircraftTypeDraft({
    required this.code,
    required this.family,
    required this.longName,
    required this.manufacturer,
    required this.category,
    required this.engineType,
    required this.mtow,
    required this.engineCount,
    required this.multiPilot,
    required this.complex,
    required this.efis,
    required this.highPerformance,
  });

  /// Type code.
  final String code;

  /// Type family.
  final String family;

  /// Human-readable long type name.
  final String longName;

  /// Manufacturer display name.
  final String manufacturer;

  /// Aircraft category.
  final AircraftCategory category;

  /// Engine type.
  final EngineType engineType;

  /// Maximum takeoff weight.
  final int mtow;

  /// Engine count.
  final int engineCount;

  /// Whether the type is multipilot.
  final bool multiPilot;

  /// Whether the type is complex.
  final bool complex;

  /// Whether the type uses EFIS.
  final bool efis;

  /// Whether the type is high performance.
  final bool highPerformance;
}

/// Shared aircraft draft used by normalized records.
class ImportedAircraftDraft {
  /// Creates an aircraft draft.
  const ImportedAircraftDraft({
    required this.registration,
    required this.mtow,
    required this.isSimulator,
    this.notes = '',
  });

  /// Registration.
  final String registration;

  /// Aircraft MTOW.
  final int? mtow;

  /// Whether the row is a simulator device.
  final bool isSimulator;

  /// Optional aircraft notes.
  final String notes;
}

/// Shared crew draft used by normalized records.
class ImportedCrewDraft {
  /// Creates a crew draft.
  const ImportedCrewDraft({
    required this.name,
    this.email = '',
    this.phone = '',
    this.notes = '',
  });

  /// Crew member name.
  final String name;

  /// Crew email.
  final String email;

  /// Crew phone number.
  final String phone;

  /// Crew notes.
  final String notes;
}

/// Shared crew assignment draft.
class ImportedCrewAssignmentDraft {
  /// Creates a standard crew assignment.
  const ImportedCrewAssignmentDraft.crew({
    required this.position,
    required this.crew,
  }) : assignSelf = false,
       createSelfIfMissing = false;

  /// Creates an assignment for the current "self" crew member.
  const ImportedCrewAssignmentDraft.self({
    required this.position,
    required this.createSelfIfMissing,
  }) : crew = null,
       assignSelf = true;

  /// Assigned crew position.
  final CrewPosition position;

  /// Crew details when assigning a named crew member.
  final ImportedCrewDraft? crew;

  /// Whether the assignment targets the current self crew record.
  final bool assignSelf;

  /// Whether the self crew record may be created if missing.
  final bool createSelfIfMissing;
}

/// Shared normalized flight row.
class NormalizedFlightRecord extends NormalizedImportRecord {
  /// Creates a normalized flight record.
  const NormalizedFlightRecord({
    required int progressOrdinal,
    required this.departureAirport,
    required this.arrivalAirport,
    required this.aircraftType,
    required this.aircraft,
    required this.departureDateTime,
    required this.arrivalDateTime,
    required this.timePicMinutes,
    required this.timePicusMinutes,
    required this.timeSicMinutes,
    required this.timeDualMinutes,
    required this.timeInstructorMinutes,
    required this.timeIfrMinutes,
    required this.timeInstrumentMinutes,
    required this.timeSimulatedInstrumentMinutes,
    required this.timeNightMinutes,
    required this.timeCrossCountryMinutes,
    required this.timeCustom1Minutes,
    required this.timeCustom2Minutes,
    required this.timeCustom3Minutes,
    required this.timeCustom4Minutes,
    required this.timeFlightMinutes,
    required this.timeBlockMinutes,
    required this.timeTotalBlockMinutes,
    required this.distanceNm,
    required this.ifrApproaches,
    required this.takeoffsDay,
    required this.takeoffsNight,
    required this.landingsDay,
    required this.landingsNight,
    required this.pilotFunction,
    required this.approachType,
    required this.remarks,
    required this.notes,
    required this.crewAssignments,
    this.takeOffDateTime,
    this.landingDateTime,
    this.matchExistingByFlightDateKey = false,
    this.overrideMatchedFlight = false,
  }) : super(progressOrdinal);

  final ImportedAirportDraft departureAirport;
  final ImportedAirportDraft arrivalAirport;
  final ImportedAircraftTypeDraft aircraftType;
  final ImportedAircraftDraft aircraft;
  final DateTime departureDateTime;
  final DateTime? takeOffDateTime;
  final DateTime? landingDateTime;
  final DateTime? arrivalDateTime;
  final int timePicMinutes;
  final int timePicusMinutes;
  final int timeSicMinutes;
  final int timeDualMinutes;
  final int timeInstructorMinutes;
  final int timeIfrMinutes;
  final int timeInstrumentMinutes;
  final int timeSimulatedInstrumentMinutes;
  final int timeNightMinutes;
  final int timeCrossCountryMinutes;
  final int timeCustom1Minutes;
  final int timeCustom2Minutes;
  final int timeCustom3Minutes;
  final int timeCustom4Minutes;
  final int timeFlightMinutes;
  final int timeBlockMinutes;
  final int? timeTotalBlockMinutes;
  final int distanceNm;
  final int ifrApproaches;
  final int takeoffsDay;
  final int takeoffsNight;
  final int landingsDay;
  final int landingsNight;
  final String pilotFunction;
  final String approachType;
  final String remarks;
  final String notes;
  final List<ImportedCrewAssignmentDraft> crewAssignments;
  final bool matchExistingByFlightDateKey;
  final bool overrideMatchedFlight;
}

/// Shared normalized positioning row.
class NormalizedPositioningRecord extends NormalizedImportRecord {
  /// Creates a normalized positioning record.
  const NormalizedPositioningRecord({
    required int progressOrdinal,
    required this.departureAirport,
    required this.arrivalAirport,
    required this.departureDateTime,
    required this.arrivalDateTime,
    required this.timeTotalMinutes,
    required this.notes,
    this.matchExistingByPositioningDateKey = false,
    this.overrideMatchedPositioning = false,
  }) : super(progressOrdinal);

  final ImportedAirportDraft departureAirport;
  final ImportedAirportDraft arrivalAirport;
  final DateTime departureDateTime;
  final DateTime? arrivalDateTime;
  final int timeTotalMinutes;
  final String notes;
  final bool matchExistingByPositioningDateKey;
  final bool overrideMatchedPositioning;
}

/// Shared normalized simulator row.
class NormalizedSimulatorRecord extends NormalizedImportRecord {
  /// Creates a normalized simulator record.
  const NormalizedSimulatorRecord({
    required int progressOrdinal,
    required this.aircraftType,
    required this.aircraft,
    required this.startDateTime,
    required this.endDateTime,
    required this.timeTotal,
    required this.remarks,
    required this.notes,
    required this.crewAssignments,
  }) : super(progressOrdinal);

  final ImportedAircraftTypeDraft aircraftType;
  final ImportedAircraftDraft aircraft;
  final DateTime startDateTime;
  final DateTime? endDateTime;
  final int timeTotal;
  final String remarks;
  final String notes;
  final List<ImportedCrewAssignmentDraft> crewAssignments;
}
