import 'dart:io';
import 'dart:typed_data';

import 'package:sqlite3/sqlite3.dart' as sqlite;

/// Detected database source kind for a selected sqlite file.
enum SimpleLogDatabaseSourceKind {
  /// Database generated by this SimpleLog app and safe for full restore.
  currentSimpleLog,

  /// Legacy SimpleLog schema that must go through migration import.
  legacySimpleLog,

  /// Unrecognized database schema.
  unknown,
}

/// Result returned after inspecting sqlite bytes.
class SimpleLogDatabaseSourceInspection {
  /// Creates an inspection result.
  const SimpleLogDatabaseSourceInspection({
    required this.kind,
    required this.isSqlite,
  });

  /// Detected source kind.
  final SimpleLogDatabaseSourceKind kind;

  /// Whether the inspected payload is a sqlite file.
  final bool isSqlite;
}

/// Classifies database files by sqlite schema.
class SimpleLogDatabaseSourceDetector {
  /// Creates a detector.
  const SimpleLogDatabaseSourceDetector();

  static const _sqliteMagic = 'SQLite format 3\u0000';

  static const Set<String> _requiredCurrentTables = <String>{
    'aircraft_types',
    'aircrafts',
    'airports',
    'crew',
    'duty_periods',
    'flight_crew_assignments',
    'flights',
    'limit_rules',
    'positionings',
    'previous_experiences',
    'report_templates',
    'rule_snapshots',
    'simulator_crew_assignments',
    'simulator_trainings',
    'time_lines',
    'user_profiles',
  };

  static const Set<String> _requiredLegacyTables = <String>{
    'model',
    'aircraft',
    'airport',
    'crew',
    'flight',
  };

  /// Inspects [bytes] and classifies the database schema.
  Future<SimpleLogDatabaseSourceInspection> inspectBytes(
    Uint8List bytes,
  ) async {
    if (!_looksLikeSqlite(bytes)) {
      return const SimpleLogDatabaseSourceInspection(
        kind: SimpleLogDatabaseSourceKind.unknown,
        isSqlite: false,
      );
    }

    final tempPath = await _writeTempFile(bytes);
    sqlite.Database? source;
    try {
      source = sqlite.sqlite3.open(tempPath);
      final tableNames = _readTableNames(source);
      if (_requiredCurrentTables.every(tableNames.contains)) {
        return const SimpleLogDatabaseSourceInspection(
          kind: SimpleLogDatabaseSourceKind.currentSimpleLog,
          isSqlite: true,
        );
      }
      if (_requiredLegacyTables.every(tableNames.contains)) {
        return const SimpleLogDatabaseSourceInspection(
          kind: SimpleLogDatabaseSourceKind.legacySimpleLog,
          isSqlite: true,
        );
      }
      return const SimpleLogDatabaseSourceInspection(
        kind: SimpleLogDatabaseSourceKind.unknown,
        isSqlite: true,
      );
    } on Object {
      return const SimpleLogDatabaseSourceInspection(
        kind: SimpleLogDatabaseSourceKind.unknown,
        isSqlite: true,
      );
    } finally {
      source?.close();
      final file = File(tempPath);
      if (file.existsSync()) {
        await file.delete();
      }
    }
  }

  bool _looksLikeSqlite(Uint8List bytes) {
    if (bytes.length < _sqliteMagic.length) {
      return false;
    }
    final header = String.fromCharCodes(bytes.sublist(0, _sqliteMagic.length));
    return header == _sqliteMagic;
  }

  Future<String> _writeTempFile(Uint8List bytes) async {
    final timestamp = DateTime.now().microsecondsSinceEpoch;
    final fileName = 'simplelog_schema_inspect_$timestamp.sqlite';
    final path =
        '${Directory.systemTemp.path}${Platform.pathSeparator}$fileName';
    final file = File(path);
    await file.writeAsBytes(bytes, flush: true);
    return path;
  }

  Set<String> _readTableNames(sqlite.Database source) {
    final rows = source.select(
      "SELECT name FROM sqlite_master WHERE type='table'",
    );
    return rows
        .map((row) => row['name']?.toString().trim().toLowerCase() ?? '')
        .where((name) => name.isNotEmpty)
        .toSet();
  }
}
